Check for binary existince
Signed-off-by: Jesse Szwedko <jesse@szwedko.me>

diff --git a/bin/run-concurrency-test b/bin/run-concurrency-test
--- a/bin/run-concurrency-test
+++ b/bin/run-concurrency-test
@@ -1,6 +1,14 @@
 #!/bin/bash
 set -euo pipefail
 
+for cmd in jq gnuplot ruby ; do
+  if ! command -v "${cmd}" &> /dev/null
+  then
+    echo "${cmd} could not be found"
+    exit
+  fi
+done
+
 DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
 
 VECTOR="${VECTOR:-vector}"
